server:
  port: 8080
  servlet:
    context-path: /sushi-store
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SUSHI_STORE;encrypt=false;trustServerCertificate=true
    username: sa
    password: root
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
jwt:
  signerKey: "%i[s3smF)6ofE+kgHv$u{J4)m-Rx4?Hq"
